###Recover all movie by genre
GET http://localhost:3000/api/movie-genre

###Create movie genre
POST http://localhost:3000/api/movie-genre/
Content-Type: application/json

{
    "movieId": 3,
    "genreId": 2
}
