###Recover all movies
GET http://localhost:3000/api/movies

###Recover a movie by id
GET http://localhost:3000/api/movies/1

###Recover a movie by genre
GET http://localhost:3000/api/movies?genre=Action

###Create a movie
POST http://localhost:3000/api/movies
Content-Type: application/json

{
  "title": "The Dark Knight",
  "year": 2008,
  "director": "Christopher Nolan",
  "duration": 152,
  "poster": "https://i.ebayimg.com/images/g/yokAAOSw8w1YARbm/s-l1200.jpg",
  "genre": ["Action", "Crime", "Drama"],
  "rate": 9.0
}

###Update a movie
PATCH  http://localhost:3000/api/movies/1
Content-Type: application/json

{
  "title": "The Shawshank Redemption Edited",
  "year": 1995
}

###Delete a movie
DELETE http://localhost:3000/api/movies/1
